import crafttweaker.api.tag.manager.ITagManager;
import crafttweaker.api.tag.MCTag;


<tagmanager:items>.addId(<tag:items:minecraft:fertilize_coral>, <resource:minecraft:fire_coral>, <resource:minecraft:horn_coral>, <resource:minecraft:bubble_coral>, <resource:minecraft:tube_coral>, <resource:minecraft:brain_coral>);
<tag:entity_types:crafttweaker:enemytier1>.add(<entitytype:betteranimalsplus:bobbit_worm>, <entitytype:betteranimalsplus:piranha>, <entitytype:betteranimalsplus:tarantula>, <entitytype:creeperoverhaul:badlands_creeper>, <entitytype:creeperoverhaul:beach_creeper>, <entitytype:creeperoverhaul:cave_creeper>, <entitytype:creeperoverhaul:dark_oak_creeper>, <entitytype:creeperoverhaul:desert_creeper>, <entitytype:creeperoverhaul:dripstone_creeper>, <entitytype:creeperoverhaul:hills_creeper>, <entitytype:creeperoverhaul:jungle_creeper>, <entitytype:creeperoverhaul:spruce_creeper>, <entitytype:creeperoverhaul:swamp_creeper>, <entitytype:minecolonies:amazon>, <entitytype:minecolonies:amazonspearman>, <entitytype:minecolonies:archerbarbarian>, <entitytype:minecolonies:archermummy>, <entitytype:minecolonies:archerpirate>, <entitytype:minecolonies:barbarian>, <entitytype:minecolonies:mummy>, <entitytype:minecolonies:norsemenarcher>, <entitytype:minecolonies:pharao>, <entitytype:minecolonies:pirate>, <entitytype:minecraft:blaze>, <entitytype:minecraft:cave_spider>, <entitytype:minecraft:creeper>, <entitytype:minecraft:drowned>, <entitytype:minecraft:enderman>, <entitytype:minecraft:endermite>, <entitytype:minecraft:guardian>, <entitytype:minecraft:hoglin>, <entitytype:minecraft:husk>, <entitytype:minecraft:illusioner>, <entitytype:minecraft:phantom>, <entitytype:minecraft:piglin>, <entitytype:minecraft:pillager>, <entitytype:minecraft:shulker>, <entitytype:minecraft:skeleton>, <entitytype:minecraft:spider>, <entitytype:minecraft:vindicator>, <entitytype:minecraft:witch>, <entitytype:minecraft:wither_skeleton>, <entitytype:minecraft:zombie>, <entitytype:minecraft:zombie_villager>, <entitytype:minecraft:zombified_piglin>, <entitytype:rottencreatures:burned>, <entitytype:rottencreatures:frostbitten>, <entitytype:rottencreatures:glacial_hunter>, <entitytype:rottencreatures:mummy>, <entitytype:rottencreatures:skeleton_lackey>, <entitytype:rottencreatures:swampy>, <entitytype:rottencreatures:undead_miner>, <entitytype:minecraft:stray>, <entitytype:rottencreatures:zombie_lackey>);
<tag:entity_types:crafttweaker:enemytier2>.add(<entitytype:minecraft:piglin_brute>, <entitytype:minecraft:ravager>, <entitytype:minecraft:warden>, <entitytype:minecraft:zombie_horse>);
<tag:entity_types:crafttweaker:bosstier2>.add(<entitytype:rottencreatures:immortal>, <entitytype:minecraft:wither>, <entitytype:minecraft:elder_guardian>, <entitytype:minecraft:ender_dragon>);
<tag:items:crafttweaker:emerald_ores>.addId(<resource:minecraft:emerald_ore>, <resource:minecraft:deepslate_emerald_ore>);
<tag:items:crafttweaker:all_froglight>.add(<item:minecraft:pearlescent_froglight>, <item:minecraft:ochre_froglight>, <item:minecraft:verdant_froglight>);